#!/usr/bin/env bash
# This file is part of the Roaster project 
# https://github.com/dmedri/roaster/
# Copyright (c) 2019-2021 Daniele Medri.
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.                                

#
# Roaster base settings
#

# where I am
RRC=$(pwd)

# R virtual environment location
RVE="$HOME/RVE"

# Roaster home
RCO="$HOME/.roaster"

# Roaster server builds home
SRV="/opt/R"

# Ask to build or not a standard version?
BSTDASK=false



#
# Libraries
#
source lib/libroaster.sh

# Start here
check-roaster-working-dirs

# Roaster build settings
SRCU="$MIRROR/src/base/"
SRCF="R-latest.tar.gz"
SRCD="VERSION-INFO.dcf"
CRANM="CRAN_mirrors.csv"

# Header
roaster-header

# Commands: evaluate status
check-cmdreq {bash,awk,cat,cut,tar,pwd,wget,grep,sudo}
if [[ $RBTYPE = "branch" || $RBTYPE = "trunk" ]]; then
	check-cmdreq {svn,git}
fi

# Help menu
while [[ -n "$1" ]]; do
	case $1 in
	"--check-status")
		check-rstable-latest
		check-status
		;;
	"--mirrors")
		roaster-mirrors-list
		;;
	"--autoclean")
		roaster-autoclean
		;;
	"--factory-reset")
		roaster-factory-reset
		;;
	"--settings")
		app-settings
		;;
	"--setup")
		roaster-setup
		;;
	"--svn-repo-branches")
		svn-repo-branches
		;;
	"--svn-repo-update-all")
		svn-repo-update-all
		;;
	"--svn-repo-fetch-all")
		svn-repo-fetch-all
		;;
	"--build-server")
		check-rstable-latest
		BTYPE="Server (in system)"
		BOPTS="$OPTSRV"
		R-build-init
		R-build-ask
		R-build-server
		;;
	"--build-standard")
		check-rstable-latest
		BTYPE="Standard (in system)"
		BOPTS="$OPTSTD"
		R-build-init
		R-build-ask
		R-build-standard
		;;
	"--build-virtualenv")
		check-rstable-latest
		BTYPE="Virtual Environment (in userspace)"
		BOPTS="$OPTRVE"
		R-build-init
		R-build-ask
		R-build-virtualenv
		;;
	"--help")
		app-options
		;;
	esac
	shift
done
freemem
